version: '3'

services:
  database:
    image: postgres:17
    container_name: ${POSTGRES_CONTAINER_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  backend:
    build: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - database

volumes:
  postgres_data:
