version: '3'

services:
  database:
    image: postgres:17
    container_name: ${POSTGRES_CONTAINER_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:7.4.1
    volumes:
      - redis_data:/data
    expose:
      - ${REDIS_PORT}
    env_file:
      - .env
  
  backend:
    build: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - database
      - redis

volumes:
  postgres_data:
  redis_data:
